INSERT INTO public.estado(id, id_pais, nombre) VALUES (1,1,'Aguascalientes');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (2,1,'Baja California');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (3,1,'Baja California Sur');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (4,1,'Campeche');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (5,1,'Coahuila de Zaragoza');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (6,1,'Colima');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (7,1,'Chiapas');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (8,1,'Chihuahua');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (9,1,'Ciudad de México');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (10,1,'Durango');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (11,1,'Guanajuato');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (12,1,'Guerrero');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (13,1,'Hidalgo');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (14,1,'Jalisco');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (15,1,'México');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (16,1,'Michoacán de Ocampo');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (17,1,'Morelos');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (18,1,'Nayarit');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (19,1,'Nuevo León');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (20,1,'Oaxaca');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (21,1,'Puebla');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (22,1,'Querétaro');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (23,1,'Quintana Roo');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (24,1,'San Luis Potosí');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (25,1,'Sinaloa');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (26,1,'Sonora');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (27,1,'Tabasco');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (28,1,'Tamaulipas');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (29,1,'Tlaxcala');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (30,1,'Veracruz de Ignacio de la Llave');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (31,1,'Yucatán');
INSERT INTO public.estado(id, id_pais, nombre) VALUES (32,1,'Zacatecas');